### ISSUE TITLE
Video is private

### ISSUE THREAD

**Issue by JoeSpizz** [learn-co-curriculum/phase-3-lecture-videos-class-methods#1]
### Canvas Link

https://learning.flatironschool.com/courses/5302/pages/video-class-methods?module_item_id=398049

### Concern

The video is private. It says I don't have permission to view it. The error message does apologize though so that's nice. 

### Suggested Changes

make it public!

**Comment by lizbur10** [comment]
Hi @JoeSpizz - there's currently a problem with the Venmo account. It should be cleared up soon. Apologies for the inconvenience. 💙
